### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by andrewcrook** [candid82/homebrew-brew#2]
https://github.com/candid82/homebrew-brew/blob/8d310c85ed422f0dead0ea4dd861301bdb2514ab/joker.rb#L14

Homebrew 3.3.0
Homebrew/homebrew-core (git revision eba45552269; last commit 2021-10-25)
Homebrew/homebrew-cask (git revision ce669fb231; last commit 2021-10-25)

From todays brew update

`Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the candid82/brew tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/candid82/homebrew-brew/joker.rb:14`

**Comment by andrewcrook** [comment]
Added Pull Request #3

**Comment by candid82** [comment]
Thanks!
